### ISSUE TITLE
docs issues

### ISSUE THREAD

**Issue by esheldon** [biggles-plot/biggles-plot.github.io#3]
for the convenience functions in the quick start

- I would move that to the top so newbies see it can be *very* easy to plot something
- the example should be even simpler

```python
plot(x, yA)
```

also note that one types `plot(..., type=)` rather than `symboltype`.  The code internally figures out if you have requested a point or line.

**Comment by beckermr** [comment]
Cool. This issue belongs on the biggles repo since the docs are stored there. I will move it.
